#!/bin/bash

cd $(dirname $0)/../../aries-cloudagent-python/scripts

docker build -t aries-cloudagent-run -f ../docker/Dockerfile.run .. || exit 1

# WARNING there is '--user root' dont use for production. it's only for testing purposes
docker run --rm -ti --name "aries-cloudagent-runner.alice" --user root --network=von_von -p 8082:80 -p 8002:8002 aries-cloudagent-run start \
 --seed 00000000000000000000000000Agent2 \
 --wallet-key welldone \
 --wallet-name myWallet \
 --wallet-type indy \
 --genesis-url http://von_webserver_1:8000/genesis \
 --inbound-transport http 0.0.0.0 8002 \
 --outbound-transport http \
 --admin 0.0.0.0 80 \
 --admin-insecure-mode \
 --log-level DEBUG \
 -l "Alice"