#!/bin/bash

cd $(dirname $0)/../../aries-cloudagent-python/scripts

docker build -t aries-cloudagent-run -f ../docker/Dockerfile.run .. || exit 1

# WARNING there is '--user root' dont use for production. it's only for testing purposes
docker run --rm -ti --name "aries-cloudagent-runner.faber" --user root --network=von_von -p 8081:80 -p 8001:8001 aries-cloudagent-run start \
 --seed 00000000000000000000000000Agent1 \
 --wallet-key welldone \
 --wallet-name myWallet \
 --wallet-type indy \
 --genesis-url http://von_webserver_1:8000/genesis \
 --inbound-transport http 0.0.0.0 8001 \
 --outbound-transport http \
 --admin 0.0.0.0 80 \
 --admin-insecure-mode \
 --endpoint http://aries-cloudagent-runner.faber:8001 \
 --invite-label "Faber invitation" \
 -l "Faber" 

# trace https://github.com/hyperledger/aries-rfcs/tree/master/features/0034-message-tracing
#  --trace \
#  --trace-target "http://webhook:1080" \
#  --trace-label "Faber trace" \
# known issue --trace-target "message" returns error https://github.com/hyperledger/aries-cloudagent-python/blob/e8e7ee2d199169c7fd7b0ca1ea737cba79a3447c/aries_cloudagent/utils/tracing.py#L206