#!/bin/bash

cd $(dirname $0)
cd  ../../aries-cloudagent-python/scripts

docker build -t aries-cloudagent-run -f ../docker/Dockerfile.run .. || exit 1

docker run --rm -ti --name "aries_cloudagent_runner_faber" --network=von_von -p 8081:8081 -p 8001:8001 aries-cloudagent-run start \
 --seed 00000000000000000000000000Agent1 \
 --wallet-key welldone \
 --wallet-name myWallet \
 --wallet-type indy \
 --genesis-url http://von_webserver_1:8000/genesis \
 --inbound-transport http 0.0.0.0 8001 \
 --outbound-transport http \
 --admin 0.0.0.0 8081 \
 --admin-insecure-mode \
 --endpoint http://172.26.0.7:8001 \
 --log-level DEBUG \
 --invite-label "Faber invitation" \
 --trace-label "Faber trace" \
 -l "Faber"

#  --endpoint http://aries_cloudagent_runner_faber:8001 \