#!/bin/bash

cd $(dirname $0)
cd  ../../aries-cloudagent-python/scripts

docker build -t aries-cloudagent-run -f ../docker/Dockerfile.run .. || exit 1

docker run --rm -ti --name "aries_cloudagent_runner_alice" --network=von_von -p 8082:8082 -p 8002:8002 aries-cloudagent-run start \
 --seed 00000000000000000000000000Agent2 \
 --wallet-key welldone \
 --wallet-name myWallet \
 --wallet-type indy \
 --genesis-url http://von_webserver_1:8000/genesis \
 --inbound-transport http 0.0.0.0 8002 \
 --outbound-transport http \
 --admin 0.0.0.0 8082 \
 --admin-insecure-mode \
 --log-level DEBUG \
 -l "Alice"
# --auto-respond-credential-offer